name: hitchcockvisuals
favicon: null
layout_spectrum: 0.29977355850860476
typography_spectrum: 0.859113299055025
title: 'Hitchcock Visuals, Inc.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6616270677186549
  lightness: 0.26466693985275924
  saturation: 0.06847729836590588
  rhythmicContrast: 0.5181716324295849
purpose: []
